const { default: Head } = require("next/head");

export default function Seo({title}) {
    return <>
    <Head>
    <title>{title}</title>
    <meta name="description" content="Generated by create next app" />
    {/* <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no" /> 
    <link rel="icon" href="/favicon.ico" />
    <link rel="manifest" href="/manifest.json" /> 
    <meta name="theme-color" content="#000000" />
    </Head>
    </>
}

Seo.defaultProps = {
    title: 'Super'
}